services:
  todo.webapi:
    image: ${DOCKER_REGISTRY-}todowebapi
    container_name: todo.api
    build:
      context: .
      dockerfile: Todo.WebApi/Dockerfile
    ports:
      - 8180:8080
      - 8181:8081
    depends_on:
      - db
 
  db:
    image: mysql:8.0
    container_name: todo.mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: tododb
    ports:
      - "3406:3306"
    volumes:
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init-db.sql
  # db:
  #   image: postgres:13.16
  #   container_name: todo.postgresql
  #   environment:
  #     - POSTGRES_DB=tododb
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-db.sql
  #   ports:
  #     - 5434:5432

  seq:
    image: datalust/seq:latest
    container_name: todo.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5441:5341
      - 8182:80

  redis:
    image: redis:latest
    container_name: todo.redis
    restart: always
    ports:
      - '6479:6379' 